### ISSUE TITLE
Why are we storing the current Node the agent is on as a dictionary?

### ISSUE THREAD

**Issue by DanielPerezJensen** [DanielPerezJensen/mapc-uva#47]
In graph.py we are storing self.current like this:

`self.current = {agent_id: self.nodes[(0, 0)]}`

Why are we storing our current node like this instead of as a coordinate? Even though in the rest of the functions we always use the location of nodes instead of the specific instance of a node? Can we atleast add a variable that tracks the current location as a pair of coordinates?

**Comment by dorian4840** [comment]
There isn't a specific reason why we store the Node object instead of the coordinates.

We noticed that the agents in the graph need to store more than just their current location (energy and attached blocks, for example), so we will change `self.current = {agent_id: self.nodes[(0, 0)]}` to something like `self.info {agent_id: {'node': self.nodes[(0, 0)], 'energy': 300}}`. Then we could make separate keys for the node object and the location. It's just that by simple doing Node.location you can get the location of the node, so storing the location as well just seems like an unnecessary thing to keep track of.

We could only store the location and not the Node Object itself, but then we would have to change the entire code for something that doesn't add extra clarify or practical value

**Comment by DanielPerezJensen** [comment]
That makes sense, but the reason I find it a bit unwieldy is this, I want to check if a given node is the node an agent is currently located in. Because of the dictionary structure I hvae to do it like this:

```python
if node.location == self.beliefs.current[self._user_id].location
```

It would be nicer if we could have either:

- A function that does it for us
```python
if node.location == self.current_location()
```

or

- Simply storing it as a named variable in the Graph object
```python
if node.location == self.current_location
```

**Comment by dorian4840** [comment]
You're right, it is a bit of a mouthful. I'll create the current_location() function (if we were to do a variable we would also need to keep updating it).

**Comment by dorian4840** [comment]
I added the function current_info() to agent.py.
```
def current_info(self, info):
    if info == 'location':
        return self.beliefs.get_current(self._user_id).location
    elif info == 'node':
        return self.beliefs.get_current(self._user_id)
```

This way you can easily get the current location as well as the node, + you can easily also add other information in necessary

**Comment by DanielPerezJensen** [comment]
I would split it up as two functions, current_location() and current_node(). I'll do it in a separate branch.
